version: '3.8'
services:
  mariadb:
    image: mariadb:10.6.16
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=aml
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - UPLOAD_LIMIT=2G
      - PMA_HOST=mariadb