CREATE TABLE MediaItem (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Author VARCHAR(255) NOT NULL,
    BookCode VARCHAR(255) NOT NULL UNIQUE,
    IssueDate DATETIME NULL,
    ReturnDate DATETIME NULL,
    Genre INT NOT NULL,
    IsBorrowed BOOLEAN DEFAULT FALSE
);
